dist: xenial
language: csharp
services:
  - docker
mono: none
dotnet: 2.2
jobs:
  include:
    - stage: test
      script:
      - docker build --target build-test -t bab-test .
    - stage: deploy
      script:
      - docker build --target buuld-env -t bab .