dist: xenial
language: generic
services:
  - docker
jobs:
  include:
    - stage: test
      install:
      - docker build --target test -t bab-test .
      script:
      - docker run --rmi bab-test .
    - stage: deploy
      install:
      - docker build --target build-prod -t bab .
      script:
      - docker run --rmi bab .