dist: xenial
services:
  - docker
jobs:
  include:
    - stage: test
      script:
      - docker build --target test -t bab-test .
    - stage: deploy
      script:
      - docker build --target buuld-prod -t bab .