dist: xenial
language: csharp
mono: none
dotnet: 2.2
services:
  - docker
jobs:
  include:
    - stage: test
      install:
      - dotnet build
      script:
      - dotnet test
    - stage: deploy
      script:
      - docker build --target prod -t bab .